# Generated by Django 6.0 on 2025-12-24 04:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(max_length=50, unique=True, verbose_name='凭证号')),
                ('voucher_date', models.DateField(default=django.utils.timezone.now, verbose_name='凭证日期')),
                ('source_document', models.CharField(blank=True, max_length=50, null=True, verbose_name='来源单据')),
                ('creator', models.CharField(default='系统自动', max_length=50)),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'finance_accounting_voucher',
                'ordering': ['-voucher_date', '-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='客户名称')),
                ('contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='电话')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='地址')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 't_customer',
            },
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='企业名称')),
                ('type', models.CharField(max_length=20, verbose_name='企业类型')),
                ('registered_capital', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='注册资金')),
                ('establish_date', models.DateField(blank=True, null=True, verbose_name='成立日期')),
                ('industry', models.CharField(blank=True, max_length=50, null=True, verbose_name='所属行业')),
                ('tax_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='税务登记号')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 't_enterprise',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True, verbose_name='订单编号')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='总金额')),
                ('status', models.CharField(default='APPROVED', max_length=20, verbose_name='审核状态')),
                ('is_posted', models.BooleanField(default=False, verbose_name='是否过账')),
                ('is_settled', models.BooleanField(default=False, verbose_name='是否结清')),
                ('purchase_date', models.DateField(default=django.utils.timezone.now, verbose_name='采购日期')),
                ('credit_period', models.IntegerField(default=0, verbose_name='账期(天)')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'finance_purchase_order',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='供应商名称')),
                ('contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='电话')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='地址')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'finance_supplier',
            },
        ),
        migrations.CreateModel(
            name='AccountSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='科目编码')),
                ('name', models.CharField(max_length=50, verbose_name='科目名称')),
                ('type', models.CharField(choices=[('ASSET', '资产'), ('LIABILITY', '负债'), ('EQUITY', '权益'), ('COST', '成本'), ('PROFIT_LOSS', '损益')], max_length=20, verbose_name='科目类别')),
                ('balance_direction', models.CharField(choices=[('DEBIT', '借'), ('CREDIT', '贷')], max_length=10, verbose_name='余额方向')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='finance.accountsubject', verbose_name='父级科目')),
            ],
            options={
                'db_table': 'finance_account_subject',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.purchaseorder')),
            ],
            options={
                'db_table': 'finance_purchase_order_item',
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True, verbose_name='订单编号')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(default='APPROVED', max_length=20, verbose_name='审核状态')),
                ('is_posted', models.BooleanField(default=False, verbose_name='是否过账')),
                ('is_settled', models.BooleanField(default=False, verbose_name='是否结清')),
                ('sales_date', models.DateField(default=django.utils.timezone.now, verbose_name='销售日期')),
                ('credit_period', models.IntegerField(default=0, verbose_name='账期(天)')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.customer', verbose_name='客户')),
            ],
            options={
                'db_table': 'finance_sales_order',
            },
        ),
        migrations.CreateModel(
            name='CollectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_no', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('collect_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='CREATED', max_length=20)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.customer')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.salesorder', verbose_name='关联订单')),
            ],
            options={
                'db_table': 'finance_collection_record',
            },
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.salesorder')),
            ],
            options={
                'db_table': 'finance_sales_order_item',
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.supplier', verbose_name='供应商'),
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_no', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pay_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='CREATED', max_length=20)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.purchaseorder', verbose_name='关联订单')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.supplier')),
            ],
            options={
                'db_table': 'finance_payment_record',
            },
        ),
        migrations.CreateModel(
            name='VoucherDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=200, verbose_name='摘要')),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.accountsubject', verbose_name='科目')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='finance.accountingvoucher')),
            ],
            options={
                'db_table': 'finance_voucher_detail',
            },
        ),
    ]
