# Generated by Django 6.0 on 2025-12-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='remark',
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
