# Generated by Django 6.0 on 2025-12-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_purchaseorder_remark_purchaseorderitem_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='remark',
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
