# Generated by Django 6.0 on 2025-12-24 11:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_salesorder_remark_salesorderitem_remark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentrecord',
            options={'ordering': ['-pay_date', '-create_time']},
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='related_order',
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='is_settled',
            field=models.BooleanField(default=False, verbose_name='是否已付款'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='payment_method_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.accountsubject', verbose_name='付款科目'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.purchaseorder', verbose_name='关联采购单'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='付款金额'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='pay_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='付款日期'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='payment_no',
            field=models.CharField(max_length=50, unique=True, verbose_name='付款单号'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.supplier', verbose_name='供应商'),
        ),
    ]
