# Generated by Django 6.0 on 2025-12-24 12:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_paymentrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionrecord',
            name='collection_method_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.accountsubject', verbose_name='收款科目'),
        ),
        migrations.AddField(
            model_name='customer',
            name='default_credit_period',
            field=models.IntegerField(default=0, verbose_name='默认账期(天)'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='fiscal_year_start_month',
            field=models.IntegerField(default=1, verbose_name='财务年度起始月'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='expense_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.accountsubject', verbose_name='支出科目'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5, verbose_name='税率'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='income_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.accountsubject', verbose_name='收入科目'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5, verbose_name='税率'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_account',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='银行账户'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='default_credit_period',
            field=models.IntegerField(default=0, verbose_name='默认账期(天)'),
        ),
        migrations.AlterField(
            model_name='collectionrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='收款金额'),
        ),
        migrations.AlterField(
            model_name='collectionrecord',
            name='collect_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='收款日期'),
        ),
        migrations.AlterField(
            model_name='collectionrecord',
            name='collection_no',
            field=models.CharField(max_length=50, unique=True, verbose_name='收款单号'),
        ),
        migrations.AlterField(
            model_name='collectionrecord',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.customer', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='collectionrecord',
            name='related_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.salesorder', verbose_name='关联销售单'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='总金额'),
        ),
        migrations.AlterField(
            model_name='voucherdetail',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='贷方金额'),
        ),
        migrations.AlterField(
            model_name='voucherdetail',
            name='debit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='借方金额'),
        ),
    ]
